Feat/multi-asset scheduling (#117)
* feat: better custom date ranges for live mode (ems) and play mode (simulation), where play mode is also responsive to the minimum resolution of the shown sensor data

Signed-off-by: F.N. Claessen <felix@seita.nl>

* feat: trigger_schedule and trigger_and_get_schedule work with multi-asset flex-models

Signed-off-by: F.N. Claessen <felix@seita.nl>

* fix: TypeError: FlexMeasuresClient.trigger_and_get_schedule() missing 1 required positional argument: 'asset_id'

Signed-off-by: F.N. Claessen <felix@seita.nl>

* docs: update documentation

Signed-off-by: F.N. Claessen <felix@seita.nl>

* docs: update rst syntax

Signed-off-by: F.N. Claessen <felix@seita.nl>

* docs: prefer ISO terminology (duration instead of timedelta)

Signed-off-by: F.N. Claessen <felix@seita.nl>

* docs: add power-capacity to example

Signed-off-by: F.N. Claessen <felix@seita.nl>

* refactor: cleaner check to check if both are set or neither is set

Signed-off-by: F.N. Claessen <felix@seita.nl>

* style: end-of-file-fixer

Signed-off-by: F.N. Claessen <felix@seita.nl>

* Revert "feat: better custom date ranges for live mode (ems) and play mode (simulation), where play mode is also responsive to the minimum resolution of the shown sensor data"

This reverts commit b235e69e59cc59a1a667bd82a3b07eac82a85091.

* style: mypy

Signed-off-by: F.N. Claessen <felix@seita.nl>

* docs: clean up text

Signed-off-by: F.N. Claessen <felix@seita.nl>

* docs: remove falsehood

Signed-off-by: F.N. Claessen <felix@seita.nl>

* docs: format PyPI

Signed-off-by: F.N. Claessen <felix@seita.nl>

---------

Signed-off-by: F.N. Claessen <felix@seita.nl>
Signed-off-by: Felix Claessen <30658763+Flix6x@users.noreply.github.com>