fix: TypeError: FlexMeasuresClient.trigger_and_get_schedule() missing 1 required positional argument: 'asset_id'
Signed-off-by: F.N. Claessen <felix@seita.nl>